### ISSUE TITLE
Как активируется сессия?

### ISSUE THREAD

**Issue by vetash** [carbonsoft/tray_agent#1]
Хочу переписать агента на node js но застрял на функции авторизации. 
1 Генерируется соль по урлу через GET: http://<site>/tray_agent.php?cmd=GET_SALT&login=<login>
2 Генерируется хэш из MD5 логина в верхнем регистре, пароля в открытом виде , и соли
3 Инициализируется сессия через GET http://<site>/tray_agent.php?cmd=LOGON2&login=<login>&session=<хэш>
Попробовал сделать это вручную - но авторизация не проходит пишет "2 Имя или Пароль неверные", можете подсказать где ошибка?

**Comment by vetash** [comment]
После долгого мучения и помощи одного хорошего человека решение наконец найдено.
Для потомков: при генерации хэша перевод строки хешировать не требуется и поэтому ее надо исключить из запроса.

**Comment by strizhechenko** [comment]
то есть тупо стрипать?:)

**Comment by strizhechenko** [comment]
@vetash то есть тупо стрипать строчку?:)

**Comment by vetash** [comment]
@strizhechenko, да, когда я пытался воспроизвести авторизацию - в моем коде строка с хэшем включала break line, в этом была вся проблема :smile:
